### PR TITLE
New prompts for confirmations

### PR DESCRIPTION
**Pull request by passy**
I'd appreciate it if someone could try these locally with the unreleased `yeoman-generator` module. It works fine for me now, but I had an occasion on one machine where the cursor would be oddly misplaced when the prompts came up.

### CODE REVIEW

**Comment by addyosmani** [comment]
Nice work! Are there any specific platforms you were experiencing that bug on? Happy to try reproducing if so.

**Comment by passy** [comment]
It happened on Linux in a gnome-terminal in a tmux session. Haven't seen it again since then. It could have been just some weird interplay between some partly upgraded generators, but it would be nice to have some more people trying it.

**Comment by passy** [comment]
Works fine in the Secure Shell extension for Chrome. :)

**Comment by sindresorhus** [comment]
Works fine for me

**Comment by passy** [comment]
Thanks for testing, guys!

**Pull request merged**
