### PR TITLE
Changed all indentation to two spaces, updated jshintrc. Fixes #286.

### LINKED ISSUE #286: Inconsistent Indentation
Noticed when converting from compass to stylus according to this [gist](https://github.com/yeoman/yeoman/wiki/Stylus-integration) that jshint became very unhappy with me, which was when I noticed the default .jshintrc is set to `indent: 4`.

I'd group fixing Gruntfile.js indentation and changing the .jshintrc file with 'reasons some will not use an efficiency' helper.

If no one beats me to it, I'll set everything to 2 space indent (per [Google](http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml)] and [NPM/Node](https://www.npmjs.org/doc/coding-style.html) JavaScript style standards) and submit a pull request.

### PR DESCRIPTION
**Pull request by aendra-rininsland**
As discussed in #286, this makes generator-webapp conform to the [Yeoman community style guide](http://yeoman.io/contributing/style-guide.html).

### CODE REVIEW

**Comment by silvenon** [comment]
Thanks for submitting a PR, but first I would like a more thorough discussion :)

@sindresorhus @eddiemonge @addyosmani @passy do we want this pulled or rather make it configurable? Or both? 4 spaces does seem to go against the style guide, if I understood it correctly.

This PRs are very inconvenient because they change almost every line, but on the other hand I don't know how many people we're pissing off with the 4 spaces convention.

**Comment by aendra-rininsland** [comment]
@silvenon Understandable! I'm curious, what's the best way of making it configurable, if that's the desired route? Supply the 4-space version and then have a step that does a `sed -i /\s\s\s\s/\s\s/g *`?

TBH, I'm wanting to use generator-webapp as a tool to teach colleagues current best practices (Yeoman, Grunt, Sass, Bootstrap, jsHint, CLI and Git can all be used at various points working with it, making it absolutely terrific for that), but I'm not really willing to do so as long as it uses 4-space tabs — in addition to not conforming to Yeoman's own community standards, I almost never see 4-space tabs in HTML/CSS/JS work these days.

Thanks!

**Comment by eddiemonge** [comment]
Looks good to me. To make it configurable, it would need to be able to take a preexisting .editorconfig file (and/or .jshintrc) that has the tab width defined and then use that to set the spacing. @SBoudrias told me of a way to change the indent on the fly but I forgot what it was.

**Comment by silvenon** [comment]
I agree, it seems that 2 spaces is what most people use (myself included). We can pull this and later make it configurable. I'll wait a bit to see if we get more :+1:s

**Comment by silvenon** [comment]
Could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by aendra-rininsland** [comment]
@silvenon Apologies, 'tis done.

**Comment by aendra-rininsland** [comment]
Thank you! :+1: :shipit: :metal:

**Pull request merged**
