### PR TITLE
Add deprecation notice

### PR DESCRIPTION
**Pull request by silvenon**
@sindresorhus sounds good?

I'm not sure about Yeoman's views on Grunt vs. gulp, I don't want to be too opinionated. Last time I checked it's this:

> The Yeoman team don't have any plans on dropping our support for Grunt at all. On the contrary, we feel that both Grunt and Gulp can happily co-exist and hope to support both communities with some automation tooling as best we can.

But that seems dated.

Refs #567.

### CODE REVIEW

**Comment by sindresorhus** [comment]
@silvenon I think it would be better to say that it's unmaintained (not deprecated) and tell users we would be happy to take on new maintainers and merge PRs, but our focus is on generator-gulp-webapp.

**Comment by silvenon** [comment]
Thanks for the feedback, updated.

**Comment by silvenon** [comment]
The commit message still says "deprecation notice", my bad :sweat:

**Comment by stevemao** [comment]
@silvenon @sindresorhus I'm happy to be around and review issues or prs. Since I'm quite familiar with the yeoman-generator code base..

**Comment by stevemao** [comment]
@silvenon @sindresorhus How to apply for collaborator here?

**Comment by silvenon** [comment]
@stevemao sorry for the late response. Not sure why, but even though I'm an owner I can't seem to find the repo settings. Maybe @sindresorhus can help out with adding you as a collaborator.

**Comment by stevemao** [comment]
Thanks @silvenon :)

**Comment by sindresorhus** [comment]
Done

**Comment by stevemao** [comment]
Thanks @sindresorhus :)

**Pull request merged**
