### PR TITLE
Add assemble recipe

### PR DESCRIPTION
**Pull request by miniplus**
I tried [generator-assemble](https://github.com/assemble/generator-assemble) but it lacked some features like minification and such. Because of this I decided to add [Assemble](http://assemble.io) to the webapp generator.

As [generator-webapp](https://github.com/yeoman/generator-webapp) has more features and options, I think [generator-assemble](https://github.com/assemble/generator-assemble) should be a fork of [generator-webapp](https://github.com/yeoman/generator-webapp) with this recipe included out of the box.

In the meantime, here's a recipe for the people that would like to add it already.

Any toughts?

### CODE REVIEW

**Comment by miniplus** [comment]
Apparently there's a [major rework](https://github.com/assemble/generator-assemble/pull/43) ongoing for generator-assemble. So my second remark might be discarded.

The recipe might still be useful though.

**Comment by jonschlinkert** [comment]
:+1:

**Comment by miniplus** [comment]
Referencing Issue #528

**Comment by jonschlinkert** [comment]
awesome!

**Comment by marikunt** [comment]
@miniplus Hi, can you take a quick look on this #634

**Pull request merged**
