### PR TITLE
Fix components relative path

### PR DESCRIPTION
**Pull request by neilhem**
Fix bower components relative path

### CODE REVIEW

**Comment by silvenon** [comment]
Thanks! Could you also change the last sentence of that paragraph to resemble the change? Maybe to this:

> Treat the `bower_components` directory as if it was a sibling to the parent of `index.html`.

You can use `git commit --amend` to add that change to this same commit.

**Comment by silvenon** [comment]
Awesome. There are 3 commits now, can you please [squash](http://davidwalsh.name/squash-commits-git) them?

**Comment by neilhem** [comment]
@silvenon deleted unnecessary commits

**Comment by silvenon** [comment]
Perfect, thanks!

**Comment by eddiemonge** [comment]
I am rolling this back as it is incorrect. `grunt serve` serves the bc folder as if it was in /app so it is a sibling of `index.html`, not a sibling of the parent

**Comment by silvenon** [comment]
Oh, that's right, but the path should indeed be `../bower_components` because otherwise building won't work.

**Comment by eddiemonge** [comment]
The only place `../bower_components` should be used is in the gruntfile for building, but even then, its `./bower_components` relative to the gruntfile. Ok so maybe it also needs to be `../bower_components` in the `styles` folder to reference a component, but that has always been the case, nothing has changed there. `index.html` is still a sibling of the folder.

**Comment by silvenon** [comment]
connect is serving `bower_components` as a sibling to `index.html`, but when building, usemin is looking at the directory structure, not how connect is serving it. Using `bower_components` instead of `../bower_components` in `index.html` will break the build process. Fortunately, connect manages to serve `../bower_components` as `./bower_components`.

This project is using `../bower_components` in `index.html` for that reason.

**Comment by eddiemonge** [comment]
Usemin needs to be updated to use the style, if it doesnt already. Paths shouldnt have to change specifically for the build tool. The build tool should be smart enough (or configurable enough) to determine where the files live on the file system, while the server serves them from the web server path

**Comment by silvenon** [comment]
Well AFAIK it doesn't currently :smiley: I agree both usemin and useref should build following `connect`ed paths, that would put an end to this eternal confusion.

**Pull request merged**
