### PR TITLE
Fixed HTTP Path of images and generated images with compass and others

### PR DESCRIPTION
**Pull request by felquis**
Hi, today I had some problems with webapp generator specifically using compass images features, this pull request solve these problems.

Related #43, #35

### CODE REVIEW

**Comment by passy** [comment]
Nice, wanted to do that myself after 0.2.0 was released. Could you squash the commits?

**Comment by felquis** [comment]
@passy Man, I didn't understand "squash" :s What you want that I do?

**Comment by passy** [comment]
@felquis I hope this helps: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by sindresorhus** [comment]
@felquis here you go: http://bit.ly/Zidnwv

**Comment by kevva** [comment]
@felquis you should read this: http://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by felquis** [comment]
Thanks @kevva, @passy, @sindresorhus I didn't know the "squash commits" term.

**Comment by kevva** [comment]
Thank you @felquis!

**Comment by sindresorhus** [comment]
@felquis thanks :)

**Pull request closed without merging**
