### PR TITLE
Add `private` to `_package.json`

### PR DESCRIPTION
**Pull request by arthurvr**
This chage happened in generator-gulp-webapp as well: https://github.com/yeoman/generator-gulp-webapp/commit/00f5422f97302c260acafab9b5edc9e34e6988bc

### CODE REVIEW

**Comment by eddiemonge** [comment]
You also need to update the tests

**Comment by arthurvr** [comment]
@eddiemonge done

**Comment by silvenon** [comment]
Thanks :+1:

**Comment by arthurvr** [comment]
Should happen in some other generators as well, will do some PRs if I get to it this evening.

**Pull request merged**
