### PR TITLE
Specify where bower should look for bower.json

### PR DESCRIPTION
**Pull request by roggel2000**
Fix for #96
Now Bower will know where to look for bower.json and the installation will work out of the box for Windows machines.

### CODE REVIEW

**Comment by addyosmani** [comment]
cc @sindresorhus for a call on this

**Comment by sindresorhus** [comment]
Bower already looks in the current directory for bower.json so that change looks really moot. If it actually does something it sounds more like a Bower bug.

**Comment by roggel2000** [comment]
If this single line of code can make your product work regardless of a bower bug, why not implement it?

**Comment by sindresorhus** [comment]
@roggel we don't apply random fixes unless we know why it fixes something. The linked issue haven't been active in months and your issue sounds different and might just be a fault in your system/config. Try reinstalling bower and see if that helps.

**Comment by roggel2000** [comment]
Yeah, I kinda figured that after I posted that comment.
Now I'm wondering how I can find that fault in my system, but that is my problem, not yours to solve :)

edit: Fixed. Had a v0.4 bower that somehow took precendence over the 1.2.8 that I had installed with npm
Sorry for ever suggesting this pull request.

**Pull request closed without merging**
