### PR TITLE
'grunt build' now properly writes bower components to vendor files

### PR DESCRIPTION
**Pull request by seyDoggy**
The usemin blocks for vendor.css and vendor.js were pointed at '(.)' instead of '(app)', which resulted in bower components not being written
to these files.

### CODE REVIEW

**Comment by addyosmani** [comment]
I'm surprised that we haven't run into raised issues with bower components not being written correctly to the appropriate vendor files before now. I would have assumed `(.)` in this case would reference app/index.html (and any directories referenced would work against the same path).

@silvenon have you run into issues like this with the current setup?

**Comment by silvenon** [comment]
I'm also surprised that this hasn't come up before, but @seyDoggy is right. Though I wouldn't want to merge this just yet before we figure out what is going on.

If someone can explain to me why Modernizr builds successfully, as it doesn't have a search path defined, I'll be very happy.

**Comment by eddiemonge** [comment]
I dont think search path should be `app`. I'm not sure what is going on without testing this but that seems wrong to me.

**Comment by seyDoggy** [comment]
Not that other generators ought to be set as the bench mark, but there are other generators point to (app) as well.

**Comment by eddiemonge** [comment]
Yeah did another test and it works without this change. What version of usemin do you have in your package.json?

**Comment by seyDoggy** [comment]
Well this is embarrassing. So much time has passed that I can't for the life of me figure out what I was ever using the webapp generator for, so I can't go back and look at the dependency versions. :(

I just updated everything and created a new `yo webapp` and everything builds fine. So something, somewhere, somehow has resolved this issue for me. Still wish I could remember what I was building at the time.

**Comment by kevva** [comment]
So I guess this is fixed then? Happy to hear it works for you now :).

**Comment by seyDoggy** [comment]
I'd say it is, yes.

**Pull request closed without merging**
