### PR TITLE
fix coffee:test task

### PR DESCRIPTION
**Pull request by herebefrogs**
**Step to reproduce:**
(assume yo + grunt-cli + bower installed globally)
- yo webapp
- npm install
- delete test/spec/test.js
- create test/spec/test.coffee:
  
  describe "Give it some context", ->
- grunt coffee:test

**Expected result:**

```
Running "coffee:test" (coffee) task
File .tmp/spec/test.js created.
Done, without errors.
```

**Actual result:**

```
Running "coffee:test" (coffee) task
Done, without errors.
```

No .tmp directory created

### CODE REVIEW

**Comment by herebefrogs** [comment]
Hi @paulirish , here is the bug I mentioned after the State of jQuery keynote last Saturday at jQueryTO

**Comment by paulirish** [comment]
Oh! Thanks very much for the PR! :) awesome

**Comment by herebefrogs** [comment]
@sindresorhus, I'm in the process of getting the CLA approved by OANDA's Legal team

**Comment by herebefrogs** [comment]
@sindresorhus & @paulirish , I just emailed the CLA to cla-submissions@google.com

Let me know if anything else is required for processing this Pull Request.

**Comment by herebefrogs** [comment]
Actually, the patch doesn't apply anymore and you've fixed this issue in https://github.com/yeoman/generator-webapp/commit/40b39a5d07fc146f7688b2d8c891f9a5759a894c and https://github.com/yeoman/generator-webapp/commit/aa87f4a9fa1b31d396c750b9af1d6f90450fe82d.

Closing this Issue and Pull Request

**Comment by sindresorhus** [comment]
@jerle76 sorry about that, forgot about this PR :/

We would be happy to receive any other contribution though :)

Just let me know if you need guidance.

**Pull request closed without merging**
