### PR TITLE
Prevent the uglify task from overriding usemin

### LINKED ISSUE #30: Scripts in app/components can't be concatenated
(Not 100% sure if the bug is specific to this repo, let me know if I should move it.)

A friend at my office just told me this morning that his component scripts weren't being included in his concatenated output. He had a build block something like this:

```
<!-- build:js scripts/main.js -->
<script src="scripts/thing.js"></script>
<script src="components/jquery/jquery.js"></script>
<script src="components/something/else.js"></script>
<script src="scripts/main.js"></script>
<!-- endbuild -->
```

...but the resulting `dist/scripts/main.js` did not contain either of his `components/**.js` scripts. It was just the concatenated result of `scripts/thing.js` and `scripts/main.js`, with no jQuery or other components.
### Verifying the bug

I couldn't replicate this on my existing project (which I made using `yo webapp` a few days ago). But then I updated yo, grunt, and bower and created a new project, and I was able to replicate the bug, on a `yo webapp`–generated project, right out of the box:

```
mkdir testgrunt && cd testgrunt
npm install -g yo grunt-cli bower
yo webapp
  # ('no' to Bootstrap for Sass)
  # ('no' to RequireJS)
npm install && bower install
```

All the above completed successfully. Had a look at the directory structure; all seemed correct. Then:

```
grunt
```

Here is the command output: https://gist.github.com/callumlocke/5089736 (It all looks correct.)

But my `dist/scripts/main.js` file contains only the following line:

```
console.log("'Allo 'Allo!");
```

It **should** contain jQuery before that line, because `app/index.html` contains this:

```
<!-- build:js scripts/main.js -->
<script src="components/jquery/jquery.js"></script>
<script src="scripts/main.js"></script>
<!-- endbuild -->
```
### Workaround

I tried changing the name of the output file, like this:

```
<!-- build:js scripts/foo.js -->
<script src="components/jquery/jquery.js"></script>
<script src="scripts/main.js"></script>
<!-- endbuild -->
```

Now it works – when I run `grunt`, I get a complete `dist/scripts/foo.js`, consisting of jQuery followed by `console.log("'Allo 'Allo!");`.

### PR DESCRIPTION
**Pull request by kevva**
Comment out the uglify task since we define our build targets by using the usemin task in index.html.

Fixes #30.

### CODE REVIEW

**Comment by passy** [comment]
At the moment this is required for CoffeeScript.

**Comment by kevva** [comment]
How? The coffee files currently gets compiled into `.tmp/scripts`. The uglify task only minifies from `app/scripts`. I've also tested `build` and it successfully compiles `coffee.js` and `main.js` into `dist/scripts`.

**Comment by passy** [comment]
Hm, you're right. I can't wrap my head around this right now. I'm pretty sure there was a good reason for that. Not sure if it still applies, though. :)

**Comment by kevva** [comment]
I can't think of any scenarios where it's required out of the box.

**Pull request merged**
