### PR TITLE
Add --skip-install-message, --skip-welcome-message

### PR DESCRIPTION
**Pull request by passy**
Requires a currently unpublished version of `yeoman-generator > 0.13.0`.

/ref #124

### CODE REVIEW

**Comment by addyosmani** [comment]
LGTM. Can we publish the updates to the generator and then bring this in?

**Comment by sindresorhus** [comment]
I don't like having more flags. Why do we need the skipInstallMessage one? And instead of the skipWelcome flag, can't we just move the ASCII to be shown on exit instead?

**Comment by passy** [comment]
See #124. Flags are currently the best (only?) way to get integration with super-generators that want to call you. I do see the problem with those too that they create ugly nesting and need to be implemented for all generators separately.

**Comment by sindresorhus** [comment]
Couldn't say no to Matts puppy eyes.

**Comment by passy** [comment]
> Couldn't say no to Matts puppy eyes.

Don't blame yourself. Nobody can.

**Pull request merged**
