### PR TITLE
Update bootstrap font copy in gruntfile

### PR DESCRIPTION
**Pull request by cebor**
I think this is the way the fonts from bootstrap should be copied.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why?

**Comment by cebor** [comment]
Because the path in bootstrap.css points to '../fonts/*', and the grunt task compiles this css file it into a vendor.css in '/styles', so the fonts must be in '/fonts' and not in '/bower_components/...'

**Comment by silvenon** [comment]
This is indeed true for LESS Bootstrap, but not for Sass Bootstrap. We could configure `$icon-font-path` to look in the same place for consistency.

**Comment by cebor** [comment]
Oh sorry, i assumed that bootstrap-sass also uses relative paths like bootstrap.

**Comment by silvenon** [comment]
Also, because it's so easy to make a mistake with such a huge-ass Gruntfile, you should always run `grunt serve:dist` to check if everything works first. For example, your `Gruntfile` could have a [syntax error](https://github.com/cebor/generator-webapp/blob/b3dbae84ffe255a4937a80ea63516c389c52b144/app/templates/Gruntfile.js#L244-L245) (not your fault), or a [wrong usemin configuration](https://github.com/yeoman/generator-webapp/pull/290#issuecomment-36469129) (also not your fault).

**Comment by eddiemonge** [comment]
fixed by Pull Request #310: Install bower_components in the root directory

**Pull request closed without merging**
