### PR TITLE
bump deps

### PR DESCRIPTION
**Pull request by stevemao**

### CODE REVIEW

**Comment by silvenon** [comment]
This looks great! Did you test that it all works fine?

**Comment by stevemao** [comment]
It works fine for me. I just bumped my deps for one of my projects and it builds correctly.

**Comment by silvenon** [comment]
Ok, I'll check changelogs and pull this later, just to be safe.

**Comment by stevemao** [comment]
No worries

**Comment by arthurvr** [comment]
Ping?

**Comment by silvenon** [comment]
Hey, sorry for the delay, I'll deal with this soon. I tried it superficially and it appears this change broke CSS live reload (an additional refresh is needed), I haven't figured out why yet.

**Comment by brunowego** [comment]
+1

**Comment by stevemao** [comment]
This should be good to go?

**Comment by silvenon** [comment]
Yep, thanks :+1:

**Pull request merged**
