### PR TITLE
Added IE rendering meta tag

### PR DESCRIPTION
**Pull request by ghost**
Added the meta tag to make sure that IE uses the latest rendering engine.

### CODE REVIEW

**Comment by arthurvr** [comment]
See https://github.com/yeoman/generator-webapp/commit/c0c2e57bfebad22c30105d0ebb379dbde3b51ae6, it was removed there.

**Comment by ghost** [comment]
But there are still many people who are not using IE11 who this will still benerfit

**Comment by arthurvr** [comment]
For sure. That's the reason we still include it in h5bp too. For me this looks good to merge :+1:

**Comment by sindresorhus** [comment]
You're free to add it yourself.

**Pull request closed without merging**
