### PR TITLE
Make sourcemap actually works

### PR DESCRIPTION
**Pull request by stevemao**
There are other ways to do it but this is probably the easiest way because it avoids changing the routes.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you elaborate how it wasn't working and how this fixes it?

**Comment by stevemao** [comment]
When choosing `ruby-sass` the `sourcemap` option is not enabled. When choosing `node-sass` the `sources` url is different from the routes of the server so it cannot find the sources. We should either change the routes of the server or just make the source inline.

**Comment by stevemao** [comment]
This PR makes the `sources` inline because we have bower_components, .tmp and app/style folders so it might be harder to change the server routes.

**Comment by stevemao** [comment]
Since ruby-sass is removed this is actually more simple

**Comment by stevemao** [comment]
60c27352a50bdc0b2bece0461bdf0e3f5b18a0ea

**Comment by silvenon** [comment]
Damn, I spend many hours fixing this only to come to the same fix which was here all along. Sorry, I didn't see it, but I will give you credit in the release notes for v0.6.1. Thanks for solving it!

**Comment by stevemao** [comment]
Lol no worries. There is some slight difference. Your approach also embeds the sass sourcemap, and let autoprefixer pick up the previous sourcemap by setting it to `true`. I was trying to keep it as close to the original workflow as possible.

**Comment by silvenon** [comment]
Released [v0.6.1](https://github.com/yeoman/generator-webapp/releases/tag/v0.6.1).

Yeah, I wanted to mimic generator-gulp-webapp and thought that there might be less potential problems in the future if sourcemap was inline.

**Comment by stevemao** [comment]
:+1:

**Pull request closed without merging**
