### PR TITLE
Add engines requirement for npm >= 1.2.10

### PR DESCRIPTION
**Pull request by passy**
As suggested by @sindresorhus. This should at least give a hint to the users if they install the generator in an outdated environment. The warning they see looks like this:

screenshot from 2013-06-25 11 12 59

Related: #94

### CODE REVIEW

**Comment by sindresorhus** [comment]
@stephenplusplus mentioned peerDependencies was introduced in 1.2.10, so maybe use that as a minimum instead? Can anyone confirm that?

**Comment by addyosmani** [comment]
1.2.10 confirmed as when it was introduced as per http://blog.nodejs.org/2013/02/07/peer-dependencies/. I would favor this being used for the minimum too.

**Comment by passy** [comment]
Sure. Give me a second.

**Comment by addyosmani** [comment]
Thanks @passy!

**Comment by sindresorhus** [comment]
Awesome.

This needs to be applied to all the generators and yo.

**Comment by stephenplusplus** [comment]
`yo`
`generator-angular`
`generator-webapp`
`generator-backbone`
`generator-ember`
`generator-jquery`
`generator-generator`

^ have been hit with PRs for the update. Any other big ones we should target?

**Comment by ragingwind** [comment]
@stephenplusplus :horse_racing:

**Pull request merged**
