### PR TITLE
Rename 'yeoman' var to 'settings'

### PR DESCRIPTION
**Pull request by creynders**
Since the former makes my eyeballs bleed ;)

### CODE REVIEW

**Comment by sindresorhus** [comment]
settings => config

**Comment by creynders** [comment]
I've been using `config` myself up to now, but I'm a bit worried it might be pretty confusing to people. That they assume it refers to the full configuration object and will be doing `<%= config.connect.test.options.port %>` for instance. Since settings isn't used in grunt yet it seemed like a good name to delineate between user defined values and configuration values.

**Comment by sindresorhus** [comment]
But `settings` could also be mistaken as the full settings object in a confused mind. I don't think it's that much of a problem. I'd rather we try `config` for now.

**Comment by kevva** [comment]
I'm fine with either but @sindresorhus word is the law.

**Pull request closed without merging**
