### PR TITLE
add --allow-remote option to serve task

### PR DESCRIPTION
**Pull request by cgcgbcbc**
Now users can run `grunt serve --allow-remote` to start a remote accessible server.
I've test it manually, but I've no idea how to modify test.js to cover this...

### CODE REVIEW

**Comment by sindresorhus** [comment]
In what situation would you need this to be dynamical? Can't you just edit the port in the gruntfile?

**Comment by cgcgbcbc** [comment]
> In what situation would you need this to be dynamical? Can't you just edit the port in the gruntfile?

First of all, some front end designer want to show others the work before push his change to the repo. It may help if he has little knowledge about javascript or grunt.

Secondly, for security concern, I think it's not a good idea if someone change the host to 0.0.0.0 and commit the change into VCS. Then he should edit the Gruntfile when he need to enable remote access and then edit it back.

**Comment by sindresorhus** [comment]
Good point. Mind updating the readme too?

**Comment by cgcgbcbc** [comment]
> Good point. Mind updating the readme too?

I'm considering about it... But I can't decide where to update...
This line `Run grunt for building and grunt serve for preview*` or in `grunt-serve-note`? Can you give me some advice?

**Comment by sindresorhus** [comment]
The former.

**Comment by cgcgbcbc** [comment]
> The former.

updated.

**Comment by sindresorhus** [comment]
Thanks :)

**Comment by cgcgbcbc** [comment]
> Thanks :)

It's my honor :smile:

**Pull request closed without merging**
