### PR TITLE
replace contrib-connect with browser-sync

### PR DESCRIPTION
**Pull request by gaboesquivel**
solves https://github.com/yeoman/generator-webapp/issues/400

based on @shakyShane's gist
https://gist.github.com/shakyShane/3ef441413d7726168c4d

### CODE REVIEW

**Comment by silvenon** [comment]
Hell yeah! Seems to work fine, thanks :+1:

**Comment by gaboesquivel** [comment]
yeah :) ! Sourcemaps and autoprefixing seem to work correctly http://screencast.com/t/Q57KaOr2c

**Comment by addyosmani** [comment]
Glad to see this finally land :) Thanks for working on the patch.

**Comment by ragingwind** [comment]
:tada: :tada:

**Comment by masakura** [comment]
:+1:

**Comment by arthurvr** [comment]
Yippee! Awesome.

**Pull request merged**
