### PR TITLE
output modernizr to script/vendor folder

### LINKED ISSUE #249: why is the modernizr in dist /bower_components instead of  dist/scripts?
I'm a bit new with yeoman,  Finished a website and been using 'grunt' to make a 'final' version.

 I've been looking at the dist folder : I thought that when using the 'grunt' command alone a distribution version of the site was compiled, and that components were minified and placed in dist/scripts or dist/scripts/vendor and that there would be no trace of the bower_components folder.. but it is there with only modernizr in it...  Is that intended or is it a bug? 

In other words: why is there a bower_components folder in dist for modernizr? shouldn't all scripts be in /scripts and all css in /styles ,,.. ?

### PR DESCRIPTION
**Pull request by eddiemonge**
Fixes #249

### CODE REVIEW

**Comment by robwierzbowski** [comment]
What do you think about outputting a full development version to .tmp (so that it's never versioned), and an optimized, crawled version to dist?

**Comment by eddiemonge** [comment]
the full version shouldn't be versioned as its managed by bower. The optimized version has always gone to dist. This only changes the path to where that new file is located.

**Comment by robwierzbowski** [comment]
The Bower package isn't official, and won't necessarily be in sync with the official grunt-modernizr version. I've had issues with this in the past (https://github.com/Modernizr/Modernizr/issues/1165).

This could be a separate issue. I'd like to make outputting a dev version a standard option in grunt-modernizr, but right now I think you have to feed it a complete configuration file.

**Comment by addyosmani** [comment]
LGTM.

**Pull request merged**
