### PR TITLE
Use grunt-contrib-watch for livereload

### PR DESCRIPTION
**Pull request by sindresorhus**
https://github.com/gruntjs/grunt-contrib-watch#live-reloading

grunt-contrib-watch got support for livereload. We should convert all generators over to it asap.

<del>This is just a start as I was stopped by a potential [bug](https://github.com/intesso/connect-livereload/issues/1) in connect-livereload. @kevva @passy would you be able to look into it?</del>

### CODE REVIEW

**Comment by sindresorhus** [comment]
There's also a problem of grunt-contrib-watch going into an infinite loop when `nospawn: true` is not used.

**Comment by shama** [comment]
@sindresorhus What about just including the snippet in the `app/templates/index.html` with a comment?

**Comment by sindresorhus** [comment]
@shama I have suggested that before and people didn't seem to like it. We could of course use some kind of HTML conditional, but we require the server for Compass/Coffee compiling anyway, so why not.

**Comment by shama** [comment]
@sindresorhus Ah I see. It seems similar to including the existing modernizr or google analytics script. Just a helpful default the user could erase if they don't need it.

**Comment by sindresorhus** [comment]
Yes, but then we would have a mechanism to remove it for production, which seems like more work than just adding a middleware to the connect task we're using anyway.

**Comment by revathskumar** [comment]
@sindresorhus / @passy Is it okey to make these changes over [yeoman/generator-backbone](https://github.com/yeoman/generator-backbone)

**Comment by sindresorhus** [comment]
Yes, go for it. I was going to mention you all but forgot.

**Comment by sindresorhus** [comment]
@inkredabull @passy @PaulKinlan @ragingwind can you update your generators accordingly?

Don't use this PR though, as it's not entirely correct. See changes here: https://github.com/yeoman/generator-webapp/compare/v0.1.7...v0.2.2

**Comment by inkredabull** [comment]
Sure, perhaps not until after I/O though ;-)

**Comment by ragingwind** [comment]
I have no my laptop at this moment. Because i'm visit to google io in San Francisco for this week.  I will update asap after back to the home. Sorry for that

**Comment by jeef3** [comment]
Maybe just me, but does this break live reloading (on Windows)?

**Comment by addyosmani** [comment]
@sindresorhus does the Chrome app one have live-reload? I filed a PR for ember generator and briefly looked at chrome app but didn't see as much config in there for live reload as the others. Will look again later.

**Comment by sindresorhus** [comment]
@addyosmani don't think so

**Comment by cetchells** [comment]
@jeef3 Yes livereload  seems broken on win8 for me, Chrome doesn't refresh. The watch task runs ok, the socket.io connections seems to be active, just no refresh in the browser

**Comment by ragingwind** [comment]
@sindresorhus @addyosmani @PaulKinlan current chrome extension / app generator is not using (i removed). after manifest v2, application's entry-point has been changed to background.js, not html. but some particular page can be use, popup/option and some legacy packaged-apps. i couldn't finding out how to use with live-reload. i must be used to chrome developer mode for test / run. any idea?

**Comment by sindresorhus** [comment]
@ragingwind i don't think livereload makes sense for those, but can you still implement the other changes from the diff link in my previous comment?

**Comment by ragingwind** [comment]
@sindresorhus sorry, i've misunderstood. i'll start now.

**Pull request closed without merging**
