### PR TITLE
Copy webp and gif images to dist/

### PR DESCRIPTION
**Pull request by passy**
Livereload watches `webp` already, but as imagemin doesn't handle it, it does not get copied over `dist/` in the build step. Also GIFs were ignored so far, but unfortunately it's still the best way for stupid reaction animations.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by passy** [comment]
Done.

**Comment by sindresorhus** [comment]
danke schön

**Comment by passy** [comment]
Vær så god!

**Comment by sindresorhus** [comment]
majQa'

**Comment by passy** [comment]
:neckbeard:

**Comment by passy** [comment]
Just for reference, someone on SO stumbled across this: http://stackoverflow.com/questions/15210319/grunt-build-not-moving-images/15221034

**Pull request merged**
