### PR TITLE
Switch grunt server to grunt serve

### PR DESCRIPTION
**Pull request by robwierzbowski**
...alias server, and add deprecation message.

Addresses https://github.com/yeoman/yeoman/issues/1183.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks :)

Would you mind updating the docs in yeoman wiki too?

**Comment by robwierzbowski** [comment]
https://github.com/yeoman/yeoman/wiki/_history

Think I got them all :smile:.

**Comment by sindresorhus** [comment]
nptuajs

**Comment by sdeering** [comment]
Can I ask why Grunt Server has been switched for Grunt Serve?

**Comment by robwierzbowski** [comment]
You absolutely can. https://github.com/yeoman/yeoman/issues/1183

TL:DR, `build` and `serve` are same tense verbs.

**Pull request merged**
