### PR TITLE
Add option for Sass without Compass

### PR DESCRIPTION
**Pull request by fluke**
I've implemented it such that you choose Sass. And then you're shown a confirm prompt asking if you want Compass. I've let the majority of the code remain the same in the templates the new Sass code is demarcated by `includeSass && !includeCompass`.

**Side by side comparisons**

Execution Time (2014-03-21 08:48:27 UTC)
    sass:server    342ms  98%
    Total 349ms

Execution Time (2014-03-21 08:47:20 UTC)
    compass:server  20.4s  100%
    Total 20.4s

### CODE REVIEW

**Comment by fluke** [comment]
Fixed the tests.

**Comment by silvenon** [comment]
I tried it, the Compass option doesn't appear for me when I select Sass. Also, it may not be a good idea to hide options from users, because they won't know Compass is available until they select Sass.

**Comment by eddiemonge** [comment]
see https://github.com/yeoman/generator-webapp/issues/302#issuecomment-38306177

**Comment by fluke** [comment]
Getting an odd issue with Inquirer.js Moving through the options for the follow up question according to https://github.com/yeoman/generator-webapp/issues/302#issuecomment-38351275 causes a new prompt to be made with the cursor moved in whatever direction we wanted. https://github.com/SBoudrias/Inquirer.js/issues/102

**Comment by silvenon** [comment]
Very cool. I noticed a couple of things:
- Why did you selected Modernizr and Sass by default? @addyosmani explicitly unselected them. (For some reason :P)
- libsass is C, not Node.js
- I would capitalize Ruby, because that's the official name of the language (this is obviously a very important change :P)

Also, very cool that you noticed that grunt-sass and grunt-contrib-sass config as slightly different :+1:

**Comment by addyosmani** [comment]
For historic info: we unselected the Modernizr and Sass options by default as found that most users only want the thinnest base possible and it's mostly power-users that want these :)

**Comment by fluke** [comment]
Oh I did that so I wouldn't have to select Sass to see if the follow up question would show correctly. Simply convenience for me :P. I'll change that.

> This task uses the experimental and superfast Node.js based Sass compiler node-sass (which only compiles .scss files).

I got confused by that.

**Comment by addyosmani** [comment]
Can we rebase this and squash the commits so it's easier to merge?

**Comment by fluke** [comment]
Squashed and rebased.

**Comment by addyosmani** [comment]
Still gray on this end. Sure it's rebased?

**Comment by silvenon** [comment]
@addyosmani Are you down with the [final solution](https://github.com/yeoman/generator-webapp/issues/302#issuecomment-38428481)? Because that's the one that got implemented, I just want to make sure you agree before this gets merged.

**Comment by addyosmani** [comment]
I'm down with the final solution. cc'ing @sindresorhus for a final sanity check.

**Comment by fluke** [comment]
Whoops only squashed it. Rebased it. @addyosmani

**Comment by addyosmani** [comment]
:star: :star: :star: 

Thanks for all the work getting this in everyone!

**Comment by sindresorhus** [comment]
Thanks @kartikluke :)

**Comment by fluke** [comment]
Thanks everybody. Always wanted to contribute something substantial to open source.

**Comment by fluke** [comment]
@cjerdonek This is the PR. You can see the commits related to this. #302

**Pull request merged**
