### PR TITLE
Revv the favicon

### LINKED ISSUE #156: Rev favicon, add apple-touch-icon?
Two parts here:

There's no apple-touch-icon in the repo. H5BP is switching to providing one 150px icon by default. Should the generator do the same?

The generator follows H5BP and lets the browser automatically find favicon.ico (and apple-touch-icon-precomposed.png if it's included). But if we link them in the `head` we can rev them, which would be nice.

If people want either of these I'll write a PR.

### PR DESCRIPTION
**Pull request by robwierzbowski**
Looks like Usemin 2.0's regex picks up the favicon link, so now we can rev it.

Fixes #156 (even though it's closed :smile:).

### CODE REVIEW

**Comment by addyosmani** [comment]
Can we update this and rebase?

**Comment by addyosmani** [comment]
ping.

**Comment by robwierzbowski** [comment]
Pang. Sorry, it's been a busy couple weeks, my open source hours are scarce.

**Comment by sindresorhus** [comment]
Thanks @robwierzbowski. No worries :)

**Pull request merged**
