### PR TITLE
reload tests when test files are saved

### LINKED ISSUE #198: bootstrap-sass-official version 3> path error
version gulp-webapp 0.1.0
To reproduce after creating app that includes bootstrap
update bower to use the latest version of bootstrap-sass-official which is currently version 3.2.0
run gulp and you get a path error
The latest version of bootstrap-sass-official from bower has removed the vendor directory, looks like this is true for all bootstrap versions 3>
dir structure used to be
--bootstrap-sass-official
  --vendor
    --assets
but with the 3.2.0 version it is
--bootstrap-sass-official
  --assets

### PR DESCRIPTION
**Pull request by eddiemonge**
fixes https://github.com/yeoman/generator-webapp/issues/198

### CODE REVIEW

**Comment by addyosmani** [comment]
LGTM. Passy is going to do a second take.

**Comment by passy** [comment]
@eddiemonge How should this be used? Is that something we should add to the README? If `grunt test watch` is the supposed way, I think we need to move the `connect` part to the not-watch condition. Otherwise it will fail because the connect server is already running.

**Comment by eddiemonge** [comment]
it runs as part of `grunt serve`. When you save a spec file, it will run the unit tests. The connect:test can run alongside the normal connect as it runs on a different port. It starts up, runs the tests and then quits.

If you do `grunt test` it will run everything normally.

**Comment by passy** [comment]
Gotcha. I think I was too impatient to see the result. Working nicely!

**Pull request merged**
