### PR TITLE
Refactoring CSS Pre-Processing

### PR DESCRIPTION
**Pull request by haydenbleasel**
Pull request for [this issue](https://github.com/yeoman/generator-webapp/issues/237) consists of 2 major changes:

1) Binding Compass functions to the compassBootstrap (now includeCompass) variable. As mentioned in my issue, there was another relatively popular issue on [making the Compass grunt task optional](https://github.com/yeoman/generator-webapp/issues/114). Compass functions are now only included if the user selects to use Sass pre-processing.

2) Separate Bootstrap from Sass with Compass. This was a major change discussed between @addyosmani, @sindresorhus and myself. Rather than the previous `Bootstrap with Sass` option, the prompt is now:

```
[] Sass with Compass
[] Bootstrap
[] Modernizr
```

which results in the following 4 workflows:
- Just CSS
- Just Sass
- Bootstrap with CSS
- Bootstrap with Sass

Each workflow has been tested with `grunt` and `grunt serve` functions.

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for putting this together. 

In the short term, I favor this set of changes for improving the flexibility of our Sass/Bootstrap setup.

It does introduce one more prompt, but I wouldn't mind it given how much we've shaved off the prompts queue in recent months.

**Comment by addyosmani** [comment]
Landed \o/ 

@sindresorhus @passy I think I've mentioned before, but I still have some reservations about us auto-including in the Bootstrap plugins when you select Bootstrap. Unsure if others feel the same pain, but I always end up removing them manually.

**Comment by passy** [comment]
Woo! \o/

Maybe @stephenplusplus has an idea if we can utilize `grunt-bower-install` somehow to ease the plugin pain a bit.

**Comment by haydenbleasel** [comment]
@addyosmani - Thanks for accepting the PR. We should be able to close [this issue](https://github.com/yeoman/generator-webapp/issues/114) now as well. My first commit was binding Compass to the Sass with Compass option in the prompt.

I'll see if I can help with some of the pressing issues that are open and look for more ways to improve Yeoman. What's the status on documentation these days?

**Comment by sindresorhus** [comment]
@addyosmani yeah, i never use them either and was previously opposed to having them in by default.

**Comment by addyosmani** [comment]
@haydenbleasel We could use all the help with documentation you could offer. I'd be happy to jump into a new issue or Google doc to talk about some of the ways this could be improved.

Are you looking for smaller tasks or do you think you might have time over the next few weeks for more? :)

**Comment by addyosmani** [comment]
@sindresorhus @passy I can open up an issue for us to either a) drop the plugins or b) move them to their own prompt. Another option is for us to ask on twitter if anyone uses the plugins while scaffolding.

**Comment by sindresorhus** [comment]
@addyosmani do it. this would be so much easier if we used Insight for prompt choices ;)

**Comment by haydenbleasel** [comment]
@addyosmani @sindresorhus - Moved this convo to a new issue.

Also Addy, new issue for improving documentation? There's still [this issue](https://github.com/yeoman/yeoman/issues/829)

**Pull request merged**
