### PR TITLE
Fix for livereload failure on newly generated webapps.

### PR DESCRIPTION
**Pull request by sheenobu**
Upgraded connect-livereload and re-ordered the middleware for the lrSnippet to
fix the livereload functionality per issue https://github.com/yeoman/generator-webapp/issues/63 .

### CODE REVIEW

**Comment by juanpujol** [comment]
It works, thank you very much man.

**Comment by passy** [comment]
Yay, it does work! Thanks for spending so much time on fixing this, @sheenobu! :)

**Comment by kraftwer1** [comment]
That fix is not included in `0.2.2`, right?

**Comment by passy** [comment]
@kraftwer1 No, it's not included in a release yet.

**Comment by kraftwer1** [comment]
How can I install this module from the master so that I can continue to work with `Yeoman 1.0.beta.5`?

I've tried `npm install https://github.com/yeoman/generator-webapp.git` but there's some error saying `Silly lockfile`.

**Comment by passy** [comment]
@kraftwer1 I haven't seen that before. Can you make sure that all the deps are up-to-date and open a new issue if it persists?

**Comment by kraftwer1** [comment]
It's probably NPM-related, I've tested it with other repositories and it happened as well.

Now I installed the `master` like that:

`sudo npm -g install https://github.com/yeoman/generator-webapp/archive/master.tar.gz`

And now Yeoman works. Thanks @passy for your help and your activities in the community.

**Comment by passy** [comment]
Yay, glad it worked. :)

**Comment by sindresorhus** [comment]
@kraftwer1 you shouldn't use master as it makes it really hard for us to debug if you run into issues.

**Comment by kraftwer1** [comment]
Okay sure, I won't report any issues from master.

**Pull request merged**
