### PR TITLE
Make use of the new checkbox prompt

### PR DESCRIPTION
**Pull request by sindresorhus**
I think it looks better and is quicker to scan.

@addyosmani @passy @stephenplusplus what do you think?

screen shot 2013-07-14 at 18 25 36

### CODE REVIEW

**Comment by sindresorhus** [comment]
Tests fails since we the mock prompt would need updating.

**Comment by passy** [comment]
This is rad! :+1:

**Comment by stephenplusplus** [comment]
This approach essentially mutes the "we can't have a prompt for everything" debate. 10 prompts with 1 option each isn't doable. 1 prompt with 10 options is.

:+1:

**Comment by passy** [comment]
> This approach essentially mutes the "we can't have a prompt for everything" debate. 10 prompts with 1 option each isn't doable. 1 prompt with 10 options is.

Absolutely! Remembering the last choices would still be nice, but for the first run this is a much better approach.

**Comment by addyosmani** [comment]
I think this is much easier to scan. Very nicely done :+1:  

Could you update the mock prompt too as a part of this PR? Happy to merge this soon after.

**Comment by sindresorhus** [comment]
nvm, only the tests needed updating.

**Comment by sindresorhus** [comment]
Oh, and since Autoprefixer has worked so good I've made it checked by default to get the last bit of feedback until we remove the prompt for it sometime in the future.

**Comment by sindresorhus** [comment]
The other generators might benefit from something similar too. Hint hint ;)

**Comment by Garbee** [comment]
Thanks for this @sindresorhus. It is a really nice update to handling Yeoman.

Very well done.

**Comment by sindresorhus** [comment]
@Garbee I'm glad to hear :)

Do let us know if there are other things that could be improved.

**Pull request merged**
