### PR TITLE
Add `yo` as peerDependency

### PR DESCRIPTION
**Pull request by passy**
/re https://github.com/yeoman/generator/issues/305

Since `yo` specifies `grunt-cli` and `bower` as peerDependencies, this should allow a `npm install -g generator-webapp` to install all three of them globally. Is that right or am I missing something?

/cc @addyosmani @sindresorhus

### CODE REVIEW

**Comment by sindresorhus** [comment]
Ya, but do test just in case.

**Comment by passy** [comment]
Verified against a clean npm dir. Installing `generator-webapp` also installs bower, yo and grunt.

**Comment by sindresorhus** [comment]
<3 peerDependencies

**Comment by sindresorhus** [comment]
Lets implement it on all the things

**Pull request merged**
