### PR TITLE
Switch to official port of Bootstrap to Sass

### PR DESCRIPTION
**Pull request by silvenon**
@jlong [recommended](https://github.com/jlong/sass-bootstrap/blob/master/README.md#bootstrap--) that we use the official port in the future.

### CODE REVIEW

**Comment by silvenon** [comment]
Bootstrap's `bootstrap.js` gets imported by `bower-install`, which is unwanted. I could just ignore it via the `exclude` option, but how does `bower-install` know not to include Modernizr?

**Comment by stephenplusplus** [comment]
> how does bower-install know not to include Modernizr?

If a file is [already referenced in the HTML](https://github.com/yeoman/generator-webapp/blob/master/app/templates/index.html#L21), `grunt-bower-install` won't import it.

**Comment by silvenon** [comment]
Oh, that's very cool. Then `exclude` it is.

**Comment by addyosmani** [comment]
Changes LGTM.

**Pull request merged**
