### PR TITLE
Remove ruby Sass option

### LINKED ISSUE #484: Why is libsass installation a "no" by default?
> ? Would you like to use libsass? Read up more at
> https://github.com/andrew/node-sass#node-sass: (y/N)

I'm just curious why "no" is the default answer to this question. Is there something wrong or undesirable about libsass? I find that Sass files compile _much_ more quickly with libsass installed, like a matter of a second or two, whereas if I answer "no," Sass files take 4-5 seconds to compile.

### PR DESCRIPTION
**Pull request by arthurvr**
Removes the option to use ruby sass in favor of libsass.

Fixes #484

### CODE REVIEW

**Comment by silvenon** [comment]
Awesome! :+1: 

I'll test this later.

**Comment by arthurvr** [comment]
I could do a similar PR for generator-gulp-webapp.

**Comment by silvenon** [comment]
generator-gulp-webapp is already rocking libsass.

**Comment by arthurvr** [comment]
Ah, perfect.

**Comment by kevva** [comment]
Do note that node-sass currently doesn't work for iojs `>1.2.0`.

**Comment by arthurvr** [comment]
> Do note that node-sass currently doesn't work for iojs >1.2.0.

Oh. That's like, big deal. When do they plan to fix that?

**Comment by kevva** [comment]
https://github.com/sass/node-sass/issues/740#issuecomment-77678162

**Comment by silvenon** [comment]
So we'll have to drag Ruby Sass along for the time being then?

**Comment by arthurvr** [comment]
> So we'll have to drag Ruby Sass along for the time being then?

Sad, but I guess so :(

**Comment by silvenon** [comment]
libsass [3.2.0](https://github.com/sass/libsass/releases/tag/3.2.0) is out! We just have to wait until node sass and then grunt-sass get updated. Would you be up for rebasing this afterwards, @arthurvr?

**Comment by arthurvr** [comment]
Yup of course :)

**Comment by arthurvr** [comment]
All done @silvenon :)

**Comment by kevva** [comment]
Alright, merged! Sweeeet.

**Comment by silvenon** [comment]
Thanks! :+1:

**Pull request merged**
