### PR TITLE
grunt-rev integration (updated)

### PR DESCRIPTION
**Pull request by passy**
I took @cbas' PR, squashed the commits and updated it to match the new globbing schema.

### CODE REVIEW

**Comment by sebdeckers** [comment]
@passy Thanks!

**Comment by passy** [comment]
@cbas You're welcome!

I just noticed that this breaks CoffeeScript support, because the compiled `.coffee` files gets revved in `.tmp/scripts/` and is subsequently not found by usemin. We need to find a solution before we merge this.

**Comment by sebdeckers** [comment]
@passy Currently `grunt-rev` simply renames the file in place. It doesn't copy them to the destination path. Something to fix in `grunt-rev`, not `generator-webapp`, I think.

**Comment by kevva** [comment]
I would perform the `rev` task on the assets in `dist` and not in `app` or `.tmp`. The `rev` task also has to be run after `uglify` `cssmin` etc, basically at the end before `usemin`.

Works for me. See kevva/generator-webapp@cdc76b3.

**Comment by passy** [comment]
Makes sense. I'm going to upgrade the PR to that.

**Comment by kevva** [comment]
You need to fix the build task too with the right targets.

**Comment by passy** [comment]
After `uglify`, right?

**Comment by kevva** [comment]
After `copy`, I think. The fonts, `.webp` and `.gif` files won't get revved now since they are copied over. On the other hand, I don't know if that will work anyway. Have to test that.

**Comment by passy** [comment]
Right. I'm going to do some manual testing tonight to see if we didn't miss anything.

**Comment by passy** [comment]
Alright, this seems to work as expected. However, this breaks any reference to resources from any place but HTML files, e. g. `url()` directives within CSS. How are those supposed to be used?

**Comment by kevva** [comment]
Strange. I thought the usemin task handled those.

@sleeper @cbas

**Comment by passy** [comment]
@kevva It does, I guess it must have been a caching issue. If you depend on a fixed path in JS you can still disable it easily enough. That should cover everything then or can you think of another edge case?

**Comment by kevva** [comment]
> If you depend on a fixed path in JS you can still disable it easily enough. 

Yes, I believe there's an issue for JS on the usemin repo too.

> That should cover everything then or can you think of another edge case?

Yeah, that should do it.

**Comment by sebdeckers** [comment]
The `usemin` task does support cache manifest nor source maps, afaik. It works reasonably well with most CSS and HTML references. You also want to run `rev` after RequireJS Optimizer.

**Comment by passy** [comment]
@sindresorhus Want to take another look? lgtm

**Comment by sindresorhus** [comment]
@passy lgtm. feel free to merge when the merge conflict is fixed. also needs committed to the angular generator.

**Pull request merged**
