### PR TITLE
Fix compile sass files with .sass extension

### PR DESCRIPTION
**Pull request by artofhuman**

### CODE REVIEW

**Comment by eddiemonge** [comment]
better format would be like whats on https://github.com/artofhuman/generator-webapp/blob/master/app/templates/Gruntfile.js#L42

Another questions is do people use .sass extension?

**Comment by kevva** [comment]
Do people use Sass?

**Comment by addyosmani** [comment]
@kevva They do. We've decided recently to move away from using Compass but Sass is still afaik heavily used.

**Comment by eddiemonge** [comment]
I think the question should have been:

> Do people use `.sass`?

**Comment by kevva** [comment]
No, I was just kidding around, hehehe.

**Comment by eddiemonge** [comment]
I wasn't. My question still stands

**Comment by eddiemonge** [comment]
@artofhuman make the code like this: `['*.{scss,sass}']` and I'll accept it.

Sidenote, why are the `server` and `dist` files for _Sass_ the same?

**Comment by artofhuman** [comment]
@eddiemonge /cc

People use sass ext. =) For example author autoprefixer use sass in https://github.com/ai/evil-front

**Pull request merged**
