### PR TITLE
Replace grunt-rev with grunt-filerev

### PR DESCRIPTION
**Pull request by stevemao**

### CODE REVIEW

**Comment by silvenon** [comment]
Why? grunt-filerev seems better maintained.

**Comment by stevemao** [comment]
Excuse my english. Changed.

**Comment by silvenon** [comment]
It appears grunt-filerev doesn't work with the [files object format](http://gruntjs.com/configuring-tasks#files-object-format), but it does with the [compact format](http://gruntjs.com/configuring-tasks#compact-format). Could you apply these changes?

``` diff
     filerev: {
       dist: {
-        files: {
-          src: [
-            '<%= config.dist %>/scripts/{,*/}*.js',
-            '<%= config.dist %>/styles/{,*/}*.css',
-            '<%= config.dist %>/images/{,*/}*.*',
-            '<%= config.dist %>/styles/fonts/{,*/}*.*',
-            '<%= config.dist %>/*.{ico,png}'
-          ]
-        }
+        src: [
+          '<%= config.dist %>/scripts/{,*/}*.js',
+          '<%= config.dist %>/styles/{,*/}*.css',
+          '<%= config.dist %>/images/{,*/}*.*',
+          '<%= config.dist %>/styles/fonts/{,*/}*.*',
+          '<%= config.dist %>/*.{ico,png}'
+        ]
       }
     },
```

I.e. just remove the `files` wrapper.

**Comment by stevemao** [comment]
```
files: {
  src: [
    '<%%= config.dist %>/scripts/{,*/}*.js',
    '<%%= config.dist %>/styles/{,*/}*.css',
    '<%%= config.dist %>/images/{,*/}*.*',
    '<%%= config.dist %>/styles/fonts/{,*/}*.*',
    '<%%= config.dist %>/*.{ico,png}'
  ]
}
```

Is actually a special use case of files object format? No wonder it doesn't work and I got confused.

**Comment by stevemao** [comment]
Made the change. Thank you :smile_cat:

**Pull request merged**
